"""create medications table

Revision ID: 05e10e98e731
Revises: 41d27d2bf5b1
Create Date: 2026-07-15 15:49:38.954096

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05e10e98e731'
down_revision: Union[str, Sequence[str], None] = '41d27d2bf5b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medications',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('patient_profile_id', sa.Uuid(), nullable=False),
    sa.Column('medicine_name', sa.String(), nullable=False),
    sa.Column('dosage', sa.Float(), nullable=False),
    sa.Column('dosage_unit', sa.Enum('MG', 'G', 'ML', 'TABLET', 'CAPSULE', 'DROP', 'PUFF', 'UNIT', name='dosageunit'), nullable=False),
    sa.Column('frequency', sa.Enum('ONCE_DAILY', 'TWICE_DAILY', 'THREE_TIMES_DAILY', 'FOUR_TIMES_DAILY', 'EVERY_OTHER_DAY', 'WEEKLY', 'AS_NEEDED', name='medicationfrequency'), nullable=False),
    sa.Column('instructions', sa.String(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['patient_profile_id'], ['patient_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('medications')
    # ### end Alembic commands ###
