"""create health metrics table

Revision ID: 41d27d2bf5b1
Revises: 5dad86cc1f4b
Create Date: 2026-07-14 17:37:22.665702

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41d27d2bf5b1'
down_revision: Union[str, Sequence[str], None] = '5dad86cc1f4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('health_metrics',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('patient_profile_id', sa.Uuid(), nullable=False),
    sa.Column('metric_type', sa.Enum('HEART_RATE', 'STEPS', 'CALORIES_BURNED', 'WEIGHT', 'BLOOD_PRESSURE_SYSTOLIC', 'BLOOD_PRESSURE_DIASTOLIC', 'BLOOD_GLUCOSE', 'SPO2', 'BODY_TEMPERATURE', 'SLEEP_DURATION', name='metrictype'), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('source', sa.Enum('MANUAL', 'GOOGLE_HEALTH', 'FITBIT', name='metricsource'), nullable=False),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['patient_profile_id'], ['patient_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_health_metrics_patient_profile_recorded_at', 'health_metrics', ['patient_profile_id', 'recorded_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_health_metrics_patient_profile_recorded_at', table_name='health_metrics')
    op.drop_table('health_metrics')
    # ### end Alembic commands ###
