"""add weight_kg field into patient profile table

Revision ID: 7973bcd94bad
Revises: f80615ff22b9
Create Date: 2026-07-27 15:58:15.186597

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7973bcd94bad'
down_revision: Union[str, Sequence[str], None] = 'f80615ff22b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema: Harden the column to NOT NULL."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 🚀 THE FIX: Manually alter the column constraint to non-nullable!
    op.alter_column(
        'patient_profiles', 
        'weight_kg',
        existing_type=sa.Float(),
        nullable=False
    )
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema: Revert column back to allowing NULL values."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 🔒 Balance: Safely allow nulls again if we ever need to roll back this version!
    op.alter_column(
        'patient_profiles', 
        'weight_kg',
        existing_type=sa.Float(),
        nullable=True
    )
    
    # ### end Alembic commands ###
