"""create patient profile table

Revision ID: dc4d57d1989e
Revises: ed8d0a4ecb47
Create Date: 2026-07-13 15:17:32.946584

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dc4d57d1989e'
down_revision: Union[str, Sequence[str], None] = 'ed8d0a4ecb47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patient_profiles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('gender', sa.Enum('MALE', 'FEMALE', 'TRANSGENDER', 'PREFER_NOT_TO_SAY', name='gender'), nullable=False),
    sa.Column('height_cm', sa.Float(), nullable=False),
    sa.Column('blood_group', sa.Enum('A_POSITIVE', 'A_NEGATIVE', 'B_POSITIVE', 'B_NEGATIVE', 'AB_POSITIVE', 'AB_NEGATIVE', 'O_POSITIVE', 'O_NEGATIVE', name='bloodgroup'), nullable=False),
    sa.Column('smoking_status', sa.Enum('NEVER', 'CURRENT_REGULAR', 'CURRENT_OCCASIONAL', 'FORMER', 'PREFER_NOT_TO_SAY', name='smokingstatus'), nullable=False),
    sa.Column('drinking_status', sa.Enum('NEVER', 'CURRENT_REGULAR', 'CURRENT_SOCIAL', 'FORMER', 'PREFER_NOT_TO_SAY', name='drinkingstatus'), nullable=False),
    sa.Column('allergies', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('chronic_conditions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('emergency_contact_name', sa.String(length=100), nullable=True),
    sa.Column('emergency_contact_phone', sa.String(length=20), nullable=True),
    sa.Column('emergency_contact_relationship', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('patient_profiles')
    # ### end Alembic commands ###
