"""add weight_kg field into patient profile table

Revision ID: f80615ff22b9
Revises: 5075812fb590
Create Date: 2026-07-27 15:49:30.456222

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f80615ff22b9'
down_revision: Union[str, Sequence[str], None] = '5075812fb590'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patient_profiles', sa.Column('weight_kg', sa.Float(), nullable=False, server_default='0.0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patient_profiles', 'weight_kg')
    # ### end Alembic commands ###
